name = "sk-houston"
compatibility_date = "2024-03-19"

[site]
bucket = "/"
entry-point = "/"

[build]
command = "npm install wrangler"
output_dir = "/"

[env.production]
name = "sk-houston"
vars.ENVIRONMENT = "production"

[env.development]
name = "sk-houston-dev"
vars.ENVIRONMENT = "development" 